name: GeneratorPlugin
version: '1.0-SNAPSHOT'
main: org.filizes.generatorplugin.Main
load: STARTUP
authors: [FILIZES]
description: RoomsGenerator by FILIZES
depend:
  - WorldEdit
commands:
  generaterooms:
    description: Генерация зон
    usage: /generaterooms
  clearroom:
    description: удалить зоны
    usage: /clearroom